[uploader] add file uploader TournSummary
d0nt-panic/ps-stat pull request #4
Opened 2017-07-27 22:16 UTC by d0nt-panic

- TournSummary -  по названию папки в которую сохраняет ps.
- Подразумевается загрузка нескольких файлов. Пока не знаю, возможно ли при загрузке указывать путь только на папку?). Может быть надо будет загружать архив файлов.
- Файлы наверно будут храниться до того момента, как их спарсят, а потом удалятся. (tmp)

2017-07-29 20:07 UTC, Mehonoshin requested changes
Лучше бы конечно сделать модельку tournament_summary и User has_many :tournament_summaries
И в нее сохранять ссылку на файл.
И потом мы сможем дифференцировать какие файлы обработали а какие нет

2017-07-29 20:07 UTC, Mehonoshin commented on app/uploaders/tourn_summary_uploader.rb
> +  # include CarrierWave::RMagick
комменты тут удаляй

2017-07-29 20:07 UTC, Mehonoshin commented on app/controllers/users_controller.rb
> +    result = User.create_form_schema.call(user_params)
А если юзер уже существует, и мы хотим новых данных дописать?

2017-07-29 20:07 UTC, Mehonoshin commented on app/models/user.rb
> +  mount_uploaders :tourn_summaries, TournSummaryUploader
JSON поле может хранить несколько файлов?

2017-07-29 20:07 UTC, Mehonoshin commented on app/controllers/users_controller.rb
> +    result = User.create_form_schema.call(user_params)
Нужно проверять существует ли никнейм.
Если существует - мы просто добавляем новый файл к существующему списку.

2017-07-29 20:07 UTC, Mehonoshin commented on spec/controllers/users_controller_spec.rb
> +    context 'with incorrect input' do
empty files list validation

2017-07-29 20:07 UTC, Mehonoshin commented on spec/controllers/users_controller_spec.rb
> +    context 'with incorrect input' do
in model

2017-07-29 20:07 UTC, Mehonoshin commented on db/migrate/20170727212841_add_tourn_summaries_to_users.rb
> +    add_column :users, :tourn_summaries, :json
Лучше бы конечно сделать модельку tournament_summary и User has_many :tournament_summaries
И в нее сохранять ссылку на файл.
И потом мы сможем дифференцировать какие файлы обработали а какие нет

2017-07-30 10:53 UTC, d0nt-panic commented on app/models/user.rb
> +  mount_uploaders :tourn_summaries, TournSummaryUploader
Он хранит информацию о нескольких файлах, да
https://github.com/carrierwaveuploader/carrierwave#multiple-file-uploads

2017-07-30 14:33 UTC, Mehonoshin commented
Лучше хранить файлы по отдельности, так как мы будем их процессить, лучше
чтобы они были атомарными сущностями

вс, 30 июля 2017 г. в 13:53, Yaroslav Sorokin <notifications@github.com>:

> *@d0nt-panic* commented on this pull request.
> ------------------------------
>
> In app/models/user.rb
> <https://github.com/d0nt-panic/ps-stat/pull/4#discussion_r130239246>:
>
> >  #
>
>  class User < ApplicationRecord
> +  mount_uploaders :tourn_summaries, TournSummaryUploader
>
> Он хранит информацию о нескольких файлах, да
> https://github.com/carrierwaveuploader/carrierwave#multiple-file-uploads
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/d0nt-panic/ps-stat/pull/4#discussion_r130239246>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAgGicdlU0PqYOJyFFsciaMFFyIOlBVJks5sTGCOgaJpZM4Ol6IO>
> .
>

2017-07-31 21:43 UTC, Mehonoshin commented on app/views/users/new.slim
> += form_with model: User.new do |f|
может быть использовать simple_form?

2017-07-31 21:43 UTC, Mehonoshin commented on db/migrate/20170730110415_create_tourn_summaries.rb
> +      t.json :text_files
Вообще я хотел чтобы User has_many :tourn_summary
Т.е. при загрузке для каждого из файлов мы создаем отдельную модель

2017-08-02 20:56 UTC, Mehonoshin approved these changes
Давай мерджить и переходить к парсингу файликов

2017-08-05 15:46 UTC, merged