WIP: [parser] made rough structure
d0nt-panic/ps-stat pull request #5
Opened 2017-08-05 17:17 UTC by d0nt-panic

2017-08-05 21:51 UTC, Mehonoshin requested changes

2017-08-05 21:51 UTC, Mehonoshin commented on app/jobs/application_job.rb
> -class ApplicationJob < ActiveJob::Base
Зачем удалил?)

2017-08-05 21:51 UTC, Mehonoshin commented on app/services/parse_tourn_summary.rb
> +module Types
Давай вынесем модуль в отдельный файл

2017-08-05 21:51 UTC, Mehonoshin commented on app/services/parse_tourn_summary.rb
> +class ParseTournSummary < Dry::Sturct
Parse в начале наверное не нужно

2017-08-05 21:51 UTC, Mehonoshin commented on app/services/parse_tourn_summary.rb
> +    Game.create(data)
`Game.create!(data)`

2017-08-05 21:51 UTC, Mehonoshin commented on app/services/parse_tourn_summary.rb
> +    TournSummary.find(id).update(error: error_message)
вынеси `TournSummary.find(id)` в отдельный метод с мемоизацией

2017-08-05 21:51 UTC, Mehonoshin commented on app/services/parse_tourn_summary.rb
> +    TournSummary.find(id).destroy
Давай не будем удалять, а добавим поле статуса с gem aasm в котором будем помечать статус как 'processed'

2017-08-05 21:51 UTC, Mehonoshin commented on app/models/tourn_summary.rb
> +  scope :without_errors, -> { where(error: nil) }
Давай здесь выбирать не по тексту ошибки, а по статусу aasm

2017-08-05 21:51 UTC, Mehonoshin commented on app/workers/parse_tourn_summary_worker.rb
> +    user.tourn_summaries.without_errors.each do |ts|
Давай парсить файлы не в одном потоке, а на каждый необработанный файл создавать новую job в sidekiq которая непосредственно получает id необработанного файла и обрабатывает его

2017-08-05 21:51 UTC, Mehonoshin commented on app/models/tourn_summary.rb
> +  scope :without_errors, -> { where(error: nil) }
Пусть все джобы будут activejob compatible

2017-08-05 21:51 UTC, Mehonoshin commented on app/services/parse_tourn_summary.rb
> +  def call
Давай вынесем логику парсинга из `Dry::Struct` класса.
Парсим файл в отдельном классе `TournParser`.
Он возвращает хеш с данными, который уже скармливаем Dry::Struct, его задача тупо валидировать полученные данные.
Т.е. каждую игру из файла мы валидируем по отдельности.
И стоит подумать о стратегии валидации, при ошибке данных в одной игре, мы либо скипаем ее, либо(скорее всего) фейлим парсинг всего файла.

2017-08-05 21:51 UTC, Mehonoshin commented on spec/workers/parse_tourn_summary_worker_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
В воркере тесты простые - нужно сделать mock и проверить что запускаем нужные классы. Не более того.

2017-08-06 18:06 UTC, d0nt-panic commented on app/jobs/application_job.rb
> -class ApplicationJob < ActiveJob::Base
Так вроде у нас сайдкик и AJ не нужон? Или понадобится для чего-нибудь?

2017-08-06 18:13 UTC, d0nt-panic commented on app/models/tourn_summary.rb
> +  scope :without_errors, -> { where(error: nil) }
1) ок
2) Для чего это нужно?

2017-08-06 21:20 UTC, Mehonoshin commented on app/jobs/application_job.rb
> -class ApplicationJob < ActiveJob::Base
Ну AJ это абстракция над всеми очередями, вдруг по-приколу решим слезть с сайдкика на что-нибудь еще.

2017-08-06 21:21 UTC, Mehonoshin commented on app/models/tourn_summary.rb
> +  scope :without_errors, -> { where(error: nil) }
Выше описал, чтобы не завязывать на сайдкик, ну и просто опыт AJ.
Если принципиально не хочешь - можно без AJ

2017-08-06 21:24 UTC, Mehonoshin commented on db/schema.rb
> +    t.string "aasm_state", null: false
а можем назвать колонку просто state?

2017-08-06 21:24 UTC, Mehonoshin commented on app/models/tourn_summary.rb
> +    event :failure do
лучше назвать fail
Чтобы все events были глаголами повелительного наклонения. 
Имхо так понятнее будет

2017-08-06 21:24 UTC, Mehonoshin commented on app/models/tourn_summary.rb
> +    state :error
лучше назвать failed

2017-08-06 21:31 UTC, Mehonoshin commented on app/services/tourn_parser.rb
> +class TournParser
Давай сделаем папку app/services/tournament
и соответственно модуль

```
module Tournament
  class Parser
    ...
  end
end
```

2017-08-06 21:31 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
> +            ts_object = user.tourn_summaries.create(text_file: ts)
```
  ts_object = user.tourn_summaries.create!(text_file: ts)
```

2017-08-06 21:31 UTC, Mehonoshin commented on app/services/tourn_summary_processor.rb
> +class TournSummaryProcessor
Также кладем в модуль

2017-08-06 21:31 UTC, Mehonoshin commented on app/services/tourn_summary_processor.rb
> +    TournValidator(data_hash) # TODO: write class
В файле много однотипных данных?

2017-08-06 21:31 UTC, Mehonoshin commented on app/services/tourn_summary_processor.rb
> +    tourn_summary.update(error_message: error_message)
`update!`

2017-08-08 21:03 UTC, d0nt-panic commented
Так как методы очень похожие, думаю отдельно вынести в константу хэш
```ruby
{
  line: 1, regex: %r{№(?<tourney_number>\d+)},
  line: 2, regex: %r{\$(?<buy_in>\d+\.\d+)\/\$(?<rake>\d+\.\d+)}
}
```

И ещё думаю стоит ли в парсере приводить результирующие данные к нужному типа, или сделать это где-то дальше ( как пример в тесте указаны все строки, но за комментами их значения, которые нужно будет записать в базу)

2017-08-08 21:09 UTC, Mehonoshin requested changes

2017-08-08 21:09 UTC, Mehonoshin commented on app/services/tournament/parser.rb
> +        when 0 then tourney_number(line)
Лучше сделать
```
def parse_line(line_number, line)
  parser = line_parser_for(line_number)
  send(parser, line)
end

def line_parser_for(line_number)
  line_parsers[line_number] || : find_user_place_and_reward
end

def line_parsers
{
0 => :tourner_number,
1 => ...
}
end
```

2017-08-08 21:09 UTC, Mehonoshin commented on app/services/tournament/parser.rb
> +        when 0 then tourney_number(line)
А впоследствии вынести каждый метод в класс типа
```
class PlayersLineParser < LineParser
  private

  def pattern
    /\[(?<started_at>.*)\]/
  end
end

class LineParser
  def initialize(line)
    @line = line
  end

  def parse
    @line.match(pattern).named_captures
  end

  def pattern
    fail NotImplementedError, 'Implement in child class'
  end
end
```

2017-08-08 21:11 UTC, Mehonoshin commented on app/services/tournament/parser.rb
> +        when 0 then tourney_number(line)
С таким подходом каждый парсер можно изолированно тестить, что очень хорошо

2017-08-09 22:18 UTC, d0nt-panic commented
В общем виде парсер закончен.. По крайней мере тест проходит. Но там ещё рефакторить и рефакторить..
- как минимум я напишу под каждый line_parser отдельный тест.
- подумаю над улучшением обработки некоторых краевых случаев: 
  * например, что нибудь сделать: 

```ruby 
next if line == "\n"  #  в Tournament::Parser#call
```
  * или возможно придумать получше обработку, когда паттерн не матчится.

```ruby
@parse_result = @line.match(pattern).try(:named_captures) || {}  # в Tournament::LineParser#parse
```

2017-08-09 23:07 UTC, Mehonoshin commented
Второй вариант лучше

2017-08-09 23:09 UTC, Mehonoshin commented on app/services/tournament/line_parser.rb
> +    def initialize(line, nickname)
Если nickname используется не во всех парсерах - лучше его передавать как элемент хеша

2017-08-09 23:13 UTC, Mehonoshin commented on app/services/tournament/processor.rb
> +      Tournament::Validator(data_hash) # TODO: write class
мы можем просто проверить с помощью if результат валидации?
Юзать исключения для flow control - плохо

2017-08-11 12:46 UTC, Mehonoshin commented on app/exceptions/wrong_user.rb
> +class WrongUser < StandardError; end
Давай дополнительно обернем этот эксепшен в модуль `Parser`

2017-08-11 12:47 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
> +            ParseTournSummaryWorker.perform_async(ts_id: ts_object.id, nickname: nickname)
А давай всеже парсить игры для всех игроков, а фильтровать по никнейму будем на этапе генерации аналитики

2017-08-11 12:49 UTC, Mehonoshin commented on app/services/tournament/line_parser.rb
> +      @parse_result = @line.match(pattern).try(:named_captures) || {}
Здесь стоит кидать исключение, если невозможно распарсить данные?
Иначе консистентность данных у нас не гарантируется

2017-08-11 12:50 UTC, Mehonoshin commented on app/services/tournament/line_parsers/find_place_and_reward.rb
> +      # private
почему закоменчено?

2017-08-11 12:53 UTC, Mehonoshin commented on app/services/tournament/parser.rb
> +    def line_parser_for(line_number)
Давай вынесем эти 2 метода в ParserRepository чтобы отвязать класс от конкретных классов парсеров

2017-08-11 12:56 UTC, Mehonoshin commented on spec/fixtures/valid_tourney.txt
> +  2: Sam (Canada),
Можем парсить и где-то хранить соперников тоже? По ним тоже можно делать аналитику будет

2017-08-13 14:37 UTC, d0nt-panic commented on app/exceptions/wrong_user.rb
> +class WrongUser < StandardError; end
Чтобы было понятно, что он нигде кроме парсера не используется?

2017-08-13 14:39 UTC, d0nt-panic commented on app/forms/user/create_new_form.rb
> +            ParseTournSummaryWorker.perform_async(ts_id: ts_object.id, nickname: nickname)
Могу парсить на всякий случай. Но считаю, что потенциальным пользователям должна отображаться только та информация, которую они сами загрузили

2017-08-13 14:41 UTC, d0nt-panic commented on app/services/tournament/line_parsers/find_place_and_reward.rb
> +      # private
случайно, поправлю

2017-08-13 14:42 UTC, d0nt-panic commented on app/services/tournament/parser.rb
> +    def line_parser_for(line_number)
ок

2017-08-13 20:10 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
> +            ParseTournSummaryWorker.perform_async(ts_id: ts_object.id, nickname: nickname)
ok, пусть будет as is

2017-08-13 20:58 UTC, merged