WIP: [parser][validator]  validator example (not complete)
d0nt-panic/ps-stat pull request #6
Opened 2017-08-13 22:04 UTC by d0nt-panic

Первые наброски валидатора

2017-08-14 21:53 UTC, Mehonoshin requested changes

2017-08-14 21:53 UTC, Mehonoshin commented on app/controllers/users_controller.rb
> +    if @user
`if create_form.save` будет достаточно

2017-08-14 21:53 UTC, Mehonoshin commented on app/controllers/users_controller.rb
> +      redirect_to user_path(@user)
`redirect_to user_path(create_form.user)`

2017-08-14 21:53 UTC, Mehonoshin commented on app/controllers/users_controller.rb
> +    user_create_form = User::CreateNewForm.new(user_params.to_h)
просто `create_form`

2017-08-14 21:53 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
> +    attr_accessor :errors
` attr_accessor :errors, :user`

2017-08-14 21:53 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
> +    def run_tourn_summary_worker(ts_id, u_id)
`run_tourn_parser_worker`

2017-08-14 21:53 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
>          user = User.find_or_create_by(nickname: nickname)
Давай уберем это в контроллер

2017-08-14 21:53 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
> +    def run_tourn_summary_worker(ts_id, u_id)
слишком сокращенные имена параметров, пиши полностью

2017-08-14 21:53 UTC, Mehonoshin commented on app/forms/user/create_new_form.rb
>          if tourn_summaries
по идее этот if не нужен
и вынести этот блок в отдельный метод

2017-08-15 19:37 UTC, d0nt-panic commented on app/forms/user/create_new_form.rb
>          user = User.find_or_create_by(nickname: nickname)
Что именно?

2017-08-15 20:53 UTC, Mehonoshin approved these changes

2017-08-17 22:24 UTC, merged